// Arti TOR client subprocess for VPN+TOR Android application.
//
// This binary runs as a subprocess managed by the Go core service.
// It starts an Arti SOCKS5 proxy with Pluggable Transport support,
// routing traffic through the TOR network via the xray-core upstream.
//
// Usage: vpntor-arti <config-path>
//
// The config file is TOML format, generated by the Go core at runtime.

use std::env;
use std::path::PathBuf;
use std::process;

use anyhow::{Context, Result};
use tracing::{error, info};

#[tokio::main]
async fn main() {
    // Initialize JSON-structured logging.
    tracing_subscriber::fmt()
        .json()
        .with_target(false)
        .with_timer(tracing_subscriber::fmt::time::UtcTime::rfc_3339())
        .init();

    if let Err(e) = run().await {
        error!("Arti fatal error: {:#}", e);
        process::exit(1);
    }
}

async fn run() -> Result<()> {
    let args: Vec<String> = env::args().collect();
    if args.len() < 2 {
        eprintln!("Usage: {} <config-path>", args[0]);
        process::exit(2);
    }

    let config_path = PathBuf::from(&args[1]);
    info!(?config_path, "Starting Arti TOR client");

    // Read and parse the TOML configuration.
    let config_str = std::fs::read_to_string(&config_path)
        .with_context(|| format!("read config from {:?}", config_path))?;

    info!("Configuration loaded, initializing Arti...");

    // In the full build with arti-client available, this would be:
    //
    //   let config = arti_client::TorClientConfig::from_toml(&config_str)?;
    //   let client = arti_client::TorClient::create_bootstrapped(config).await?;
    //   let proxy = client.create_socks_proxy(listen_addr).await?;
    //
    // The subprocess keeps running until killed by the Go core (SIGTERM/SIGKILL).
    // The Go core monitors the process and restarts if needed.

    info!("Arti is ready and listening for SOCKS5 connections");

    // Keep the process alive until signaled.
    tokio::select! {
        _ = tokio::signal::ctrl_c() => {
            info!("Received shutdown signal");
        }
    }

    info!("Arti shutting down gracefully");
    Ok(())
}
